---
name: 🐛 Bug Report
about: Report a bug in the Stria language specification
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: ''
---

## Bug Description

<!-- A clear and concise description of what the bug is -->

## Location in Specification

<!-- Which section of the specification contains the bug? -->
- **Section**: 
- **Page/Line**: 
- **URL**: 

## Current Behavior

<!-- What currently happens that is incorrect? -->

## Expected Behavior

<!-- What should happen instead? -->

## Code Example

<!-- If applicable, provide a code example that demonstrates the issue -->

```stria
// Code example here
```

## Proposed Fix

<!-- If you have a suggestion for how to fix this, please describe it -->

## Additional Context

<!-- Add any other context about the problem here -->
