blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/sharo-jef/stria-spec/discussions
    about: Ask questions and discuss Stria language design with the community
  - name: 📖 Language Specification
    url: https://sharo-jef.github.io/stria-spec/
    about: Read the complete Stria language specification
  - name: 📋 Proposals
    url: https://github.com/sharo-jef/stria-spec/tree/master/proposals
    about: View existing proposals or submit a new language proposal
